apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: rajivrtk01/auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: SPRING_DATASOURCE_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # external port on node (you can choose 30000–32767)

#apiVersion: v1
#kind: Service
#metadata:
#  name: auth-service
#spec:
#  type: ClusterIP  # ⬅️ Change this
#  selector:
#    app: auth-service
#  ports:
#    - port: 8080
#      targetPort: 8080
