apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vaG9zdC5kb2NrZXIuaW50ZXJuYWw6NTQzMi90b2RvLWFwcC0x
  SPRING_DATASOURCE_USERNAME: cmFqaXY=
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=
